# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: horizon-integration-test--agent-registry-service
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: "internal-and-cloud-load-balancing"
spec:
  template:
    metadata:
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: GCP_SERVICE_ACCOUNT_PLACEHOLDER
      containers:
      - image: us-central1-docker.pkg.dev/GCP_PROJECT_ID_PLACEHOLDER/horizon-integration-test/agent-registry:latest
        ports:
        - name: http1
          containerPort: 5001
        env:
        - name: APP_URL
          value: "https://horizon-integration-test--agent-registry-service-GCP_PROJECT_NUMBER_PLACEHOLDER.us-central1.run.app"
        - name: GOOGLE_GENAI_USE_VERTEXAI
          value: "TRUE"
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
        command:
        - python
        - -m
        - demo_agent_registry
        args:
        - --host
        - "0.0.0.0"
        - --port
        - "5001"
        - --log-level
        - "info"
        - --registry-file
        - "/app/demo_agent_registry/agent_registry_cloud_run.json"